version: '3.1'

services:
  db:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_DB: myhealth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data